version: '3.5' 

services: 

    db:
      image: postgres:alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: postgres

    frontend: 
      image: frontend
      build:
        context: ../frontend
        args:
          API_URL: '/api'

      container_name: frontend-container
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:8080

    backend:
      image: backend
      build:
        context: ../backend

      container_name: backend-container
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
        
    redis:
      image: redis:latest
      container_name: redis

    nginx:
      image: nginx:alpine
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      container_name: nginx