version: '3.5' 

services: 
    db:
      image: postgres:alpine
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: postgres
      volumes:
        - ./data:/var/lib/postgresql/data

    frontend: 
      image: frontend
      ports:
        - 5000:5000
      container_name: frontend-container
      environment:
        - REACT_APP_BACKEND_URL=http://127.0.0.1:8080

    backend:
      image: backend
      ports:
        - 8080:8080
      container_name: backend-container
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      links:
        - redis

    redis:
      image: redis:latest
      container_name: redis

volumes:
  postgres_data: