version: '3.5' 

services: 

    frontend: 
      image: kurkkumopo-frontend 
      ports:
        - 3000:3000
      container_name: kurkkumopo-frontend-container

    backend:
      image: kurkkumopo-backend
      ports:
        - 5000:5000
      volumes:
        - training_data:/src/model
      container_name: kurkkumopo-backend-container

    training:
      build: kurkkumopo-training
      volumes:
        - training_data:/src/model
        - images:/src/imgs
      container_name: kurkkumopo-training-container

volumes:
    training_data:
    images: